<?php
// $Id$

/**
 * @file
 * Renders the permalinks to a node's files.
 *
 * Available variables:
 * - $attachment_links: An array of keyed attachment link arrays. Each array
 *   in this array has the following keys:
 *     - 'url' - The URL for that item's attachment.
 *     - 'weight' - The relative weight for that attachment within
 *       $attachment_links.
 *     - 'default render' - A default rendering of the item.
 * - $default_render: A default unordered list rendering for the attachment
 *   links as generated by theme('item_list',...).
 *
 * The following variables are provided for contextual information.
 * - $node: Node object the link information is being rendered for.
 * - $user: The user accessing the node.
 *
 * @see template_preprocess_attachment_links()
 * @see theme_item_list()
 */
?>

<div id="attachment-links">
  <?php print $default_render; ?>
</div>
